### ISSUE TITLE
'./docker-compose.dev.yml' is invalid

### ISSUE THREAD

**Issue by toobiwankenobi** [bibbox/sys-bibbox#74]
Hi there,

I am trying to install BIBBOX (Ubuntu 20.04) and I am following the [installation guide](https://bibbox.readthedocs.io/en/latest/installation_v4_bibbox_linux/). After running `sudo bash INSTALL.sh` upon cloning the git repo, I receive the following error at the end:  

`Error response from daemon: network with name bibbox-default-network already exists`
`ERROR: The Compose file './docker-compose.dev.yml' is invalid because:`
`services.bibbox-sys-commander-celery.depends_on contains an invalid type, it should be an array`
`services.bibbox-sys-commander-keycloak.depends_on contains an invalid type, it should be an array`
`services.bibbox-sys-commander-backend.depends_on contains an invalid type, it should be an array`
`services.bibbox-sys-commander-celery-monitor.depends_on contains an invalid type, it should be an array`
`INSTALLATION COMPLETE`

Any ideas how I can resolve this issue? It looks like an indentation issue - since this file gets created during the installation I can't do much about it I guess (except correcting it manually after installation). 

Thank you for your feedback!

**Comment by jungwire** [comment]
Hi, 
sorry for the late response did you manage to fix it?
if not please check your docker compose version and also try it with the current version of the BIBBOX as we just updated the installation procedure

**Comment by toobiwankenobi** [comment]
Hi,

`sudo apt-get install docker-compose -y`
`docker-compose is already the newest version (1.25.0-1).`

After cloning the current version, I now get a different error message:

```
Block until one or more containers stop, then print their exit codes
INSTALL.sh: line 89: [: =: unary operator expected
Building the frontend failed !
```

**Comment by AlexMartazan** [comment]
The installation procedure is divided in 2 parts so to speak. You get the error because the variable "exitcode" in your case is empty which can happen because the container that's supposed to build the frontend part doesn't start. This project is based on docker compose version 2.0+. 
I will give you a set of commands that should install docker compose 2 and all dependencies it might have:
```
sudo apt-get update
sudo apt-get install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```
Now after this please run:  `docker compose version`. 
Note: the space between "docker" and "compose" is intended.
