### ISSUE TITLE
Celery healthcheck error

### ISSUE THREAD

**Issue by Tarydium** [bibbox/sys-bibbox#77]
After solving Keycloak healthcheck setting port 9000 as porposed, i get Celery error.

ERROR: for bibbox-sys-commander-celery-monitor  Container "0d57cf512d0b" is unhealthy.

ERROR: for bibbox-sys-commander-backend  Container "0d57cf512d0b" is unhealthy.
ERROR: Encountered errors while bringing up the project.

**Comment by Tarydium** [comment]
log from celery container shows: 

I'm in DEFAULT config postgresql://postgres:postgres@postgres:5432/bibbox
I'm in DEV LOCAL config postgresql://postgres:postgres@127.0.0.1:5432/bibbox
CREATE APP IN  development  MODE
Usage: celery [OPTIONS] COMMAND [ARGS]...
Try 'celery --help' for help.

Error: Invalid value for '-A' / '--app':
Unable to load celery application.
While trying to load the module celery_worker.app_celery the following error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/keycloak/connection.py", line 224, in raw_post
    return self._s.post(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 697, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 792, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for "'http:/realms/'sys-bibbox' # name of the keycloak realm/protocol/openid-connect/token"

**Comment by Tarydium** [comment]
While trying to load the module celery_worker.app_celery the following error occurred:
i think there was a typo on  docker-compose.dev.yml `"celery_worker.app_**celerey**" `
I corrected to `"celery_worker.app_**celery**"  and still gives error.

**Comment by jungwire** [comment]
Hi [Tarydium](https://github.com/Tarydium),

Thanks for your message. We just merged the fix for the keycloak port error, as the new keycloak docker uses a different port.
We have problem replicating your errors, can you give us some information about your system?

**Comment by Tarydium** [comment]
Reisntalled my system and it worked. Maybe my previous installation was inconsistent. Thanks for your help.

**Comment by jungwire** [comment]
Thanks
